name: Check for update in a Website and notice on slack
on:
  push:
  schedule:
  - cron: "* * * * *"
jobs:
  check:
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    steps:
      - uses: r-lib/actions/setup-r@master
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages(c('magrittr', 'httr', 'stringr', 'xml2', 'glue'))"
      - name: Run script
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.INCOMING_WEBHOOK_URL }}
        run: |
          git clone --recursive https://github.com/Athospd/ghActionsTest
          cd ghActionsTest/R
          Rscript check_for_update.R
