name: Check for update in a Website and notify on slack
on:
  push:
  schedule:
  - cron: "* * * * *"
jobs:
  check:
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    steps:
      - uses: r-lib/actions/setup-r@master
      - name: Install Package Dependencies
        run: |-
          sudo apt install libcurl4-openssl-dev
          Rscript -e "install.packages(c('curl', 'magrittr', 'httr', 'stringr', 'xml2', 'glue'))"
      - name: Run script
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.INCOMING_WEBHOOK_URL }}
        run: |
          git clone --recursive https://github.com/Athospd/ghActionsTest
          cd ghActionsTest
          Rscript R/check_for_update.R
          ls -h
      - uses: actions/upload-artifact@v2
        with:
          name: current_content
          path: current_content.rds
